<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
 <?php include('Header.php') ?>

  

 <div class="container" style="margin-top:50px">
  <h2>Australia High Comission New Delhi</h2>
  <p>Address : 1/50-G, Shantipath, New Delhi, Tel : 41399900/41221000, Fax : 26887536
Email : immigration.india@dfat.gov.au , Website: www.immi.gov.au, Website: www.indiaembassy.gov.au,
</p>
<p>
VFS: Urmi Axis Bldg., 2nd Floor, Behind Famous Studio, Opp. E. Moses Road, Mahalaxmi (W), Mumbai 400011 Tel. 022-67866006 | Website: www.vfs-au-in.com</p>
  <br>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li class="nav-item" >
      <a class="nav-link active" data-toggle="tab" href="#home" style="width: auto;">Tourist Visa</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#menu1" style="width: auto;">Business Visa</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#menu2" style="width: auto;">Transit Visa</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#menu3" style="width: auto;">Download</a>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div id="home" class="container tab-pane active"><br>
      <h3 style="text-decoration: underline;">Tourist and Visit Visa Requirement </h3>
      <ol>
      	<li>Passport- Valid passport not be older than 10 years, must be valid at least SIX MONTHS longer than the intended stay. The passport must also have at least TWO BLANK PAGES to affix the visa along with all old passport booklets. Handwritten passports, Passports with observation and passports of 20-year validity are not acceptable.</li><br>
      	<li>Application Form- 1419 Visa form to be filled online. Form No. 956A (duly filled - should be typed with agent details OR handwritten but should be neat and readable.</li><br>
      	<li>Photo- 2 Recent Coloured Photograph (Fresh ones i.e. NOT used earlier for any visa) should be: - 35mm x 45mm in dimension, On matte finish paper, With White background, With 80% face coverage, non-smiling [without sunglasses, a hat/cap or other head covering, unless the applicant wears such items because of their religious belief or ethnic background].</li><br>
      	<li>Covering Letter (Addressed to Australia High Commission, New Delhi) on Letter Head with brief Company details, with mentioning duration of visit, purpose of visit, expenses clause. Details of all Applicants with name, passport number, If Applicable For Business Person Or on Plain Paper for Company Employee.</li><br>
      	<li>Confirmed Hotel Voucher as per the ticket sectors (with hotel Name, Address, Telephone no and Email. Id) with Day to Day Itinerary, Or Invitation Letter from Invitee with Passport Copy and Residence Proof, Bank Statement.</li><br>
      	<li>Confirmed Return Ticket or Round Trip Ticket Itinerary copy.</li><br>
      	<li>Bank Statements of Applicant last 6 months with Stamp and Signature form Bank with branch address and telephone numbers.</li><br>
      	<li>Occupation Proof
      		<ul>
      			<li>In case of Employee -Proof of employment (employment certificate/NOC) and Pay slip of last 3 months and Form 16 or Income Tax Copy (ITR-V) Last 03 Years</li><br>
      			<li>In case applicant is the proprietor / owner of the company Cover letter on company`s letter head, company`s Original 3 month`s bank statement (with bank seal and signature), proof of paid income tax (for 3 years), company memo, partnership deal, establishment license or proprietorship etc are required.</li><br>
      			<li>o	If the applicant is sponsored proof of sponsorship and/or private accommodation by completing a national form of the Schengen State concerned (seethe website of the Member State of destination).</li><br>
      			<li>If the applicant is retired Proof of retirement, pension statements for the last three months; - proof of regular income generated by ownership of property or business.</li><br>
      		</ul>
      	</li><br>
      	<li>For Student, Bonafied certificate from school or College must with Id card copy.</li><br>
      	<li>In case Children traveling with one Parent then NOC letter from another Parent are required. (On ₹ 100 . Stamp paper & Notarized).</li><br>
      	<li>For Honeymooner's 
      		<ul>
      			<li>Couple wedding card with Engagement Photographs.</li>
      			<li>Spouse Father / Mother Noc Letter with ID Card copy.</li>
      		</ul>
      	</li><br>
      </ol>
      <p><h4 style="text-decoration: underline;">Note:-</h4></p>
      <ul>
      	<li>Processing time will be depending on Consulate, Embassy.</li>
      	<li>The Consulate will decide validity of the visa.</li>
      	<li>Visa & Services Fees are Non-Refundable.</li>
      </ul>
    </div>
    <div id="menu1" class="container tab-pane fade"><br>
      <h3 style="text-decoration: underline;">Business Visa Requirement</h3>
        <ol>
     	 <li>Passport- Valid passport not be older than 10 years, must be valid at least SIX MONTHS longer than the intended stay. The passport must also have at least TWO BLANK PAGES to affix the visa along with all old passport booklets. Handwritten passports, Passports with observation and passports of 20-year validity are not acceptable.</li><br>
       	 <li>Application Form- 1415 Visa form to be filled online. Form No. 956A (duly filled - should be typed with agent details OR handwritten but should be neat and readable.</li><br>
      	 <li>Photo- 2 Recent Coloured Photograph (Fresh ones i.e. NOT used earlier for any visa) should be: - 35mm x 45mm in dimension, On matte finish paper, With White background, With 80% face coverage, non-smiling [without sunglasses, a hat/cap or other head covering, unless the applicant wears such items because of their religious belief or ethnic background].</li><br>
      	 <li>Covering Letter (Addressed to Australia High Commission, New Delhi) on Letter Head with brief Company details, with mentioning duration of visit, purpose of visit, expenses clause. Details of all Applicants with name, passport number, If Applicable For Business Person Or on Plain Paper for Company Employee.</li><br>
      	 <li>Invitation letter on Company letterhead with seal and address and contact number, Details like travel dates in and out, passport number, designation, a brief company profile and other details about trip and expenses.</li><br>
      	 <li>Confirmed Hotel Voucher as per the ticket sectors (with hotel Name, Address, Telephone no and Email. Id) with Day to Day Itinerary, Or Invitation Letter from Invitee with Passport Copy.</li><br>
      	 <li>Confirmed Return Ticket or Round Trip Ticket Itinerary copy.</li><br>
      	 <li>Travel Insurance Policy Coverd Travel Periode</li><br>
      	 <li>Bank Statements of Applicant last 6 months with Stamp and Signature form Bank with branch address and telephone numbers.</li><br>
      	 <li>Income Tax Paper last 03 Years</li><br>
      	 <li>Fixed Deposit and Other Investment Paper If Applicable,</li><br>
      	 <li>Occupation Proof
      		<ul>
      			<li>In case of Employee- Proof of employment (employment certificate/NOC) and Pay slip of last 3 months and  Form 16 ot Income Tax Copy(ITR-V) Last 03 Years</li><br>
      			<li>In case applicant is the proprietor, DIrector, Parter of the company Cover letter on company`s letter head ,company`s Original 3 month`s bank statement (with bank seal and signature), proof of paid income tax (for 3 years), company memo, partnership deal, establishment license or proprietorship etc are required</li><br>
      			<li>If the applicant is sponsored proof of sponsorship and/or private accommodation by completing a national form of the Schengen State concerned (seethe website of the Member State of destination)</li><br>
      		</ul>
      	</li><br>
        </ol>
        <p><h4 style="text-decoration: underline;">Note:-</h4></p>
      <ul>
      	<li>Processing time will be depending on Consulate, Embassy.</li>
      	<li>The Consulate will decide validity of the visa.</li>
      	<li>Visa & Services Fees are Non-Refundable.</li>
      </ul>  	
    </div>
    <div id="menu2" class="container tab-pane fade"><br>
      <h3>Transit Visa</h3>
      <ol>
      	<li>Passport- Valid passport not be older than 10 years, must be valid at least SIX MONTHS longer than the intended stay. The passport must also have at least TWO BLANK PAGES to affix the visa along with all old passport booklets. Handwritten passports, Passports with observation and passports of 20-year validity are not acceptable.</li><br>
      	<li>Application Form- 876 Visa form to be filled online. Form No. 956A (duly filled - should be typed with agent details OR handwritten but should be neat and readable</li><br>
      	<li>Photo- 2 Recent Colored Photograph (Fresh ones i.e. NOT used earlier for any visa) should be: - 35mm x 45mm in dimension, On matte finish paper, With White background, With 80% face coverage, non-smiling [without sunglasses, a hat/cap or other head covering, unless the applicant wears such items because of their religious belief or ethnic background</li><br>
      	<li>Covering Letter (Addressed to Australia High Commission, New Delhi) on Letter Head with brief Company details, with mentioning duration of visit, purpose of visit, expenses clause. Details of all Applicants with name, passport number, If Applicable For Business Person Or on Plain Paper for Company Employee.</li><br>
      	<li>Confirmed Return Ticket or Round Trip Ticket Itinerary copy.</li><br>
      	<li>Bank Statements of Applicant last 6 months with branch address and telephone numbers.</li><br>
      	<li>If Marriage applicant is travelling for honeymoon then Marriage certificate or Marriage Card and Engagement /Marriage Photograph are required. Occupation proof</li><br>
      	<li>Occupation Proof
      		<ul>
      			<li>In case of Employee -Proof of employment (employment certificate/NOC) and Pay slip of last 3 months and  Form 16 ot Income Tax Copy(ITR-V) Last 03 Years</li><br>
      			<li>In case applicant is the proprietor / owner of the company Cover letter on company`s letter head ,company`s Original 3 month`s bank statement (with bank seal and signature), proof of paid income tax (for 3 years), company memo, partnership deal, establishment license or proprietorship etc are required</li><br>
      			<li>If the applicant is sponsored proof of sponsorship and/or private accommodation by completing a national form of the Schengen State concerned (seethe website of the Member State of destination)</li><br>
      			<li>If the applicant is retired Proof of retirement, pension statements for the last three months; - proof of regular income generated by ownership of property or business</li><br>
      		</ul>
      	</li><br>
      	<li>If Student, leave certificate from school must with Id card copy.</li><br>
      	<li>In case Children traveling with one Parent then NOC letter from other Parent are required. (On 100 Rs. Stamp paper & Notarized).</li><br>
      	<li>For Honeymooner 
      		<ul>
      			<li>Couple wedding card with Engement Photographs</li>
      			<li> Spouse Father / Mother Noc Letter with ID Card copy</li>
      		</ul>
      	</li><br>
      </ol>
      <p><h4 style="text-decoration: underline;">Note:-</h4></p>
      <ul>
      	<li>Processing time will be depending on Consulate, Embassy.</li>
      	<li>The Consulate will decide validity of the visa.</li>
      	<li>Visa & Services Fees are Non-Refundable.</li>
      </ul>
    </div>
    <div id="menu3" class="container tab-pane fade"><br>
      <h3 style="text-decoration: underline;">Forms</h3>
      <br>
      <br>
      <br>
      <p >Tourist Visa Form 1419-
      <a style="margin-left: 48px" href="https://immi.homeaffairs.gov.au/form-listing/forms/1419.pdf" target="_blank">Click Heare</a></p>
      <p >Tourist Visa Covering letter -
      <a style="margin-left: 10px" href="https://immi.homeaffairs.gov.au/form-listing/forms/1419.pdf" target="_blank">Click Heare</a></p>
      <p >Bisness Visa Form -
      <a style="margin-left: 10px" href="https://immi.homeaffairs.gov.au/form-listing/forms/1415.pdf" target="_blank">1415</a></p>
      <p >Transit Visa Form -
      <a style="margin-left: 10px" href="https://https://www.canada.ca/content/dam/ircc/migration/ircc/english/pdf/kits/forms/imm5257e.pdf" target="_blank">876</a></p>
    </div>
</div>
</div>
</div>

 <?php include("Footer.php")?>

</body>
</html>